# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-30 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='content',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='projects',
            name='design',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='projects',
            name='usability',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
