# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-30 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0004_auto_20191030_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='posted_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
