# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-01 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0006_auto_20191030_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='proImage',
            field=models.ImageField(blank=True, upload_to='project_pics/'),
        ),
    ]
